### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wassgha** [wassgha/MirrorOS#28]
The main task at hand is to reimplement this project using technologies that can be ported into both desktop (Raspbian) and mobile (think Android tablets or iPad). The goal is to also make the project js-only by getting rid of the separate Python face recognition API.

## Short-term taks

- [ ] Find a development stack that will allow the interface to run universally on mobile and desktop
- [ ] Re-engineer the project the use the new development stack
- [ ] Re-implement the current features that the project has in node-js only:
- [ ] Face Recognition and Smile detection for logging-in to the Mirror with `opencv4nodejs`
- [ ] Constant monitoring of user presence through face detection
- [ ] Home UI with clock, date and weather
- [ ] Draggable widgets and widget structure
- [ ] Widget launcher
- [ ] Leap motion support? Touchscreen support? Tablet support?

## Long-term tasks
- [ ] Full-fledged SDK for widgets with documentation
- [ ] Communication with nearby devices (getting notification from phone, connecting to bluetooth speakers)
- [ ] Support for AirPlay and other video streaming platforms to display content on the Magic Mirror/Display
- [ ] Alexa / Google Assistant Integration 
- [ ] Companion mobile app to manage accounts and log-ins (log-in on the phone, the app uploads tokens from Facebook, Google assistant, etc to a cloud server then the mirror updates its interface accordingly)
- [ ] User accounts and face training through the mobile app
- [ ] Live selfie filters app (filter overlay on mirror)
- [ ] Uber/Lyft integration
- [ ] News app
- [ ] Live TV widget (Youtube Live TV?)
- [ ] Smart home widget (Nest, etc. integration)
- [ ] OTA updates

**Comment by Darkcast** [comment]
it would also bee col if you can add integration with smart doorbells so we can see who is outside.

**Comment by wassgha** [comment]
@mitchas
